### ISSUE TITLE
HelloWorld can't be deployed in minikube - docker image not found

### ISSUE THREAD

**Issue by cmoulliard** [spring-cloud-incubator/spring-cloud-kubernetes#55]
The deployment of the HelloWorld in minikube generates 

```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.17.1/minikube-darwin-
amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
minikube start
mvn clean package fabric8:deploy
```

generates this error

```
Failed to pull image "cloud/kubernetes-hello-world:snapshot-170324-194007-0653": Error: image cloud/kubernetes-hello-world not found
Error syncing pod, skipping: failed to "StartContainer" for "spring-boot" with ErrImagePull: "Error: image cloud/kubernetes-hello-world not found"
```

![screenshot 2017-03-24 19 40 42](https://cloud.githubusercontent.com/assets/463790/24308823/d317d39c-10c9-11e7-9aa6-47f5d0a0eb7c.png)

Kubernetes yaml file generated by f-m-p

```
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 16b4eaf0016aedfb255cce4c5ea4bc4a4a14a7f3
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      provider: fabric8
      project: kubernetes-hello-world
      version: 0.2.0.BUILD-SNAPSHOT
      group: org.springframework.cloud
    name: kubernetes-hello-world
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: kubernetes-hello-world
      provider: fabric8
      group: org.springframework.cloud
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 16b4eaf0016aedfb255cce4c5ea4bc4a4a14a7f3
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kubernetes-hello-world&var-version=0.2.0.BUILD-SNAPSHOT
      fabric8.io/docs-url: scp://static.springframework.org/var/www/domains/springframework.org/static/htdocs/spring-cloud/docs/kubernetes-hello-world/0.2.0.BUILD-SNAPSHOT/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
    labels:
      provider: fabric8
      project: kubernetes-hello-world
      version: 0.2.0.BUILD-SNAPSHOT
      group: org.springframework.cloud
    name: kubernetes-hello-world
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: kubernetes-hello-world
        provider: fabric8
        group: org.springframework.cloud
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 16b4eaf0016aedfb255cce4c5ea4bc4a4a14a7f3
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kubernetes-hello-world&var-version=0.2.0.BUILD-SNAPSHOT
          fabric8.io/docs-url: scp://static.springframework.org/var/www/domains/springframework.org/static/htdocs/spring-cloud/docs/kubernetes-hello-world/0.2.0.BUILD-SNAPSHOT/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
        labels:
          provider: fabric8
          project: kubernetes-hello-world
          version: 0.2.0.BUILD-SNAPSHOT
          group: org.springframework.cloud
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: cloud/kubernetes-hello-world:snapshot-170324-203655-0857
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          securityContext:
            privileged: false
```
